/// Flutter icons QuickBillIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
//   fonts:
//    - family:  QuickBillIcons
//      fonts:
//       - asset: fonts/QuickBillIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class QuickBillIcons {
  QuickBillIcons._();

  static const _kFontFam = 'QuickBillIcons';
  static const _kFontPkg = null;

  static const IconData bill_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loop_24px_outlined = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData notes_24px = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_24px_outlined = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings_24px = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
